### ISSUE TITLE
XE4: [dcc32 Fatal Error] F2084 Internal Error: AV07E6CBDB-R382843E0-0

### ISSUE THREAD

**Issue by edwinyzh** [malcolmgroves/FluentQuery#4]
Hi,

I'm using XE4, I get the error as stated in the topic, when trying to compile the FluentQueryTests.dpr project.

Ever worse - if the FluentQuery folder is in the 'Library Path', the error happens each time I compile any Delphi project.

Is it a compiler error of XE4? Thanks.

**Comment by malcolmgroves** [comment]
I haven't tested with XE4, but it wouldn't surprise me. FluentQuery pushes Generics pretty hard, and there were generics fixes in later compilers.
